language: java
matrix:
  include:
    - script: ant main
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ant
            - ant-optional
    - script: ./gradlew build
